<template>
    <div id="contactme">
        <div class="container _flex _center_vertical" style="height:100%">
            <p>By Thatchakon Jom-ud</p>
        </div>
    </div>
</template>
<script>
export default {
    name:"contactme"
}
</script>
<style>
    #contactme{
        margin-top: 20px;
        background-color: #7AACCC;
        width: 100%;
        height: 100px;
    }
    #contactme p {
        color: aliceblue
    }
</style>
